apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 20
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          # 여러분의 image 주소를 입력해주세요.
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_55e2dfc0f198
